# run command after the pod startup

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: alpine-deployment
  name: alpine-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpine-deployment
  template:
    metadata:
      labels:
        app: alpine-deployment
    spec:
      containers:
      - image: alpine
        imagePullPolicy: Always
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "touch /tmp/yyy"]
        name: alpine
        stdin: true
        tty: true
